version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - crop-disease-predictor

  crop-disease-predictor:
    image: crop-disease-predictor # Replace with your crop disease predictor image name
    ports:
      - "5050:5050"